### ISSUE TITLE
Self referencing loop detected for property 'task' with type

### ISSUE THREAD

**Issue by jimjja** [gocardless/gocardless-dotnet#12]
I am trying to create a new customer, and every time I make a request I get the following error : 

> Newtonsoft.Json.JsonSerializationException: Self referencing loop detected for property 'task' with type 'System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[System.Object,MyApplication.Services.GoCardlessService+<CreateCustomer>d__5]'. Path 'stateMachine.<>t__builder'.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CheckForCircularReference(JsonWriter writer, Object value, JsonProperty property, JsonContract contract, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Microsoft.AspNetCore.Mvc.Formatters.JsonOutputFormatter.WriteObject(TextWriter writer, Object value)
   at Microsoft.AspNetCore.Mvc.Formatters.JsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultAsync(IActionResult result)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResultFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

Framework: .Net Core 2.0
Reproduction Steps:
`
            var customerRequest = new GoCardless.Services.CustomerCreateRequest()
            {
                Email = "user@example.com",
                GivenName = "Frank",
                FamilyName = "Osborne",
                AddressLine1 = "27 Acer Road",
                AddressLine2 = "Apt 2",
                City = "London",
                PostalCode = "E8 3GX",
                CountryCode = "GB",
                Metadata = new Dictionary<string, string>()
                {
                  {"salesforce_id", "ABCD1234"}
                }
            };
`
`
            var customerResponse = await _service.Customers.CreateAsync(customerRequest);
            GoCardless.Resources.Customer customer = customerResponse.Customer;
`

I found a workaround solution for now which is adding Ignoring the reference Loop Handling of Newtonsoft within the startup of my project: 
`services.AddMvc().AddJsonOptions(x => x.SerializerSettings.ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Ignore);`

I hope this information is enough to reproduce. Let me know if you need more details.

**Comment by lancscoder** [comment]
Hi @jimjja,

I'm having trouble replicating your issue. I've used the code snippet you provided and it works fine without producing any errors. I've tried in both a console app and an mvc app both work fine.

Here's the console app:
```c#
class Program
{
  public static async Task Main(string[] args)
  {
    var customerRequest = new GoCardless.Services.CustomerCreateRequest()
    {
      Email = "user@example.com",
      GivenName = "Frank",
      FamilyName = "Osborne2",
      AddressLine1 = "27 Acer Road",
      AddressLine2 = "Apt 2",
      City = "London",
      PostalCode = "E8 3GX",
      CountryCode = "GB",
      Metadata = new Dictionary<string, string>() { { "salesforce_id", "ABCD1234" } }
    };

    var service = GoCardless.GoCardlessClient.Create("token", GoCardless.GoCardlessClient.Environment.SANDBOX); ;

    var customerResponse = await service.Customers.CreateAsync(customerRequest);

    GoCardless.Resources.Customer customer = customerResponse.Customer;

    Console.WriteLine(customer.GivenName);
    Console.WriteLine(customer.Id);

    Console.ReadLine();
  }
}
```

I'm using version 2.12.0 of the GoCardless nuget package.

Looking at your error message it looks like it's being thrown in this class `MyApplication.Services.GoCardlessService`, are you mapping the `GoCardless.Resources.Customer` object into a class you've created yourself and then converting it to json? 

The `GoCardless.Resources.Customer` is a flat object that doesn't reference anything else so it's strange its producing a circular reference. 

If you can provide some more of your code - perhaps the method where the error is thrown we can help you diagnose your problem further.

**Comment by jimjja** [comment]
Hi @lancscoder 
I am also using version 2.12.0 of the GoCardless nuget package.

In my GoCardlessService I have injected the GoCardlessClient which is how I use it inside the class.
The code is as follows:

```
public GoCardlessService(GoCardlessClient service)
{
	_service = service;
}

public async Task<Customer> CreateCustomer(Address billingAddress, string emailAddress, string firstName, string lastName, string companyName, int userId, string countryCode = "GB")
{
	var customerDetails = new CustomerCreateRequest()
	{
		Email = emailAddress,
		AddressLine1 = billingAddress.AddressLine1,
		AddressLine2 = billingAddress.AddressLine2,
		AddressLine3 = billingAddress.AddressLine3,
		City = billingAddress.City,
		CountryCode = countryCode,
		PostalCode = billingAddress.Postcode,
		GivenName = firstName,
		FamilyName = lastName,
		Metadata = new Dictionary<string, string>()
		{
			{"userId", userId.ToString()}
		}
	};

	var res = await _service.Customers.CreateAsync(customerDetails);
	return res.Customer;
}
```

**Comment by jimjja** [comment]
Hi @lancscoder,
I went through the code and it was my silly mistake.

It is all working fine now.
Thanks!

**Comment by ASalihov** [comment]
@jimjja and what was the mistake?

**Comment by asifshiraz** [comment]
I had the same issue. For me, (quite possibly the same 'silly mistake' as @jimjja), was that I was not awaiting the object to be serialized. So it was serializing the Task instead of the object.

**Comment by masaab** [comment]
Are you missing async and await in your method.

**Comment by UmaSathish** [comment]
I am having the same issue but I could not fix the issue.

**Comment by Kirill22012002** [comment]
I had the same problem. And I solved it. 

When i had this error
`        var result = _accountService.LoginAdminUserAsync(dto);
`
Now. It works
`        var result = await _accountService.LoginAdminUserAsync(dto);
`

If you have the same problem try to find place where did you forget `await`
